const std = @import("std");

const WeatherStation = struct {
    id: [:0]const u8,
    temp: f32,

    pub inline fn measurement(self: *WeatherStation) f32 {
        return std.crypto.random.float(f32) * 10 + self.temp;
    }
};

const file_path = "./measurements.txt";

var stations = [_]WeatherStation {
    WeatherStation{ .id = "Abha", .temp = 18.0 },
    WeatherStation{ .id = "Abidjan", .temp = 26.0 },
    WeatherStation{ .id = "Abéché", .temp = 29.4 },
    WeatherStation{ .id = "Accra", .temp = 26.4 },
    WeatherStation{ .id = "Addis Ababa", .temp = 16.0 },
    WeatherStation{ .id = "Adelaide", .temp = 17.3 },
    WeatherStation{ .id = "Aden", .temp = 29.1 },
    WeatherStation{ .id = "Ahvaz", .temp = 25.4 },
    WeatherStation{ .id = "Albuquerque", .temp = 14.0 },
    WeatherStation{ .id = "Alexandra", .temp = 11.0 },
    WeatherStation{ .id = "Alexandria", .temp = 20.0 },
    WeatherStation{ .id = "Algiers", .temp = 18.2 },
    WeatherStation{ .id = "Alice Springs", .temp = 21.0 },
    WeatherStation{ .id = "Almaty", .temp = 10.0 },
    WeatherStation{ .id = "Amsterdam", .temp = 10.2 },
    WeatherStation{ .id = "Anadyr", .temp = -6.9 },
    WeatherStation{ .id = "Anchorage", .temp = 2.8 },
    WeatherStation{ .id = "Andorra la Vella", .temp = 9.8 },
    WeatherStation{ .id = "Ankara", .temp = 12.0 },
    WeatherStation{ .id = "Antananarivo", .temp = 17.9 },
    WeatherStation{ .id = "Antsiranana", .temp = 25.2 },
    WeatherStation{ .id = "Arkhangelsk", .temp = 1.3 },
    WeatherStation{ .id = "Ashgabat", .temp = 17.1 },
    WeatherStation{ .id = "Asmara", .temp = 15.6 },
    WeatherStation{ .id = "Assab", .temp = 30.5 },
    WeatherStation{ .id = "Astana", .temp = 3.5 },
    WeatherStation{ .id = "Athens", .temp = 19.2 },
    WeatherStation{ .id = "Atlanta", .temp = 17.0 },
    WeatherStation{ .id = "Auckland", .temp = 15.2 },
    WeatherStation{ .id = "Austin", .temp = 20.7 },
    WeatherStation{ .id = "Baghdad", .temp = 22.7 },
    WeatherStation{ .id = "Baguio", .temp = 19.5 },
    WeatherStation{ .id = "Baku", .temp = 15.1 },
    WeatherStation{ .id = "Baltimore", .temp = 13.1 },
    WeatherStation{ .id = "Bamako", .temp = 27.8 },
    WeatherStation{ .id = "Bangkok", .temp = 28.6 },
    WeatherStation{ .id = "Bangui", .temp = 26.0 },
    WeatherStation{ .id = "Banjul", .temp = 26.0 },
    WeatherStation{ .id = "Barcelona", .temp = 18.2 },
    WeatherStation{ .id = "Bata", .temp = 25.1 },
    WeatherStation{ .id = "Batumi", .temp = 14.0 },
    WeatherStation{ .id = "Beijing", .temp = 12.9 },
    WeatherStation{ .id = "Beirut", .temp = 20.9 },
    WeatherStation{ .id = "Belgrade", .temp = 12.5 },
    WeatherStation{ .id = "Belize City", .temp = 26.7 },
    WeatherStation{ .id = "Benghazi", .temp = 19.9 },
    WeatherStation{ .id = "Bergen", .temp = 7.7 },
    WeatherStation{ .id = "Berlin", .temp = 10.3 },
    WeatherStation{ .id = "Bilbao", .temp = 14.7 },
    WeatherStation{ .id = "Birao", .temp = 26.5 },
    WeatherStation{ .id = "Bishkek", .temp = 11.3 },
    WeatherStation{ .id = "Bissau", .temp = 27.0 },
    WeatherStation{ .id = "Blantyre", .temp = 22.2 },
    WeatherStation{ .id = "Bloemfontein", .temp = 15.6 },
    WeatherStation{ .id = "Boise", .temp = 11.4 },
    WeatherStation{ .id = "Bordeaux", .temp = 14.2 },
    WeatherStation{ .id = "Bosaso", .temp = 30.0 },
    WeatherStation{ .id = "Boston", .temp = 10.9 },
    WeatherStation{ .id = "Bouaké", .temp = 26.0 },
    WeatherStation{ .id = "Bratislava", .temp = 10.5 },
    WeatherStation{ .id = "Brazzaville", .temp = 25.0 },
    WeatherStation{ .id = "Bridgetown", .temp = 27.0 },
    WeatherStation{ .id = "Brisbane", .temp = 21.4 },
    WeatherStation{ .id = "Brussels", .temp = 10.5 },
    WeatherStation{ .id = "Bucharest", .temp = 10.8 },
    WeatherStation{ .id = "Budapest", .temp = 11.3 },
    WeatherStation{ .id = "Bujumbura", .temp = 23.8 },
    WeatherStation{ .id = "Bulawayo", .temp = 18.9 },
    WeatherStation{ .id = "Burnie", .temp = 13.1 },
    WeatherStation{ .id = "Busan", .temp = 15.0 },
    WeatherStation{ .id = "Cabo San Lucas", .temp = 23.9 },
    WeatherStation{ .id = "Cairns", .temp = 25.0 },
    WeatherStation{ .id = "Cairo", .temp = 21.4 },
    WeatherStation{ .id = "Calgary", .temp = 4.4 },
    WeatherStation{ .id = "Canberra", .temp = 13.1 },
    WeatherStation{ .id = "Cape Town", .temp = 16.2 },
    WeatherStation{ .id = "Changsha", .temp = 17.4 },
    WeatherStation{ .id = "Charlotte", .temp = 16.1 },
    WeatherStation{ .id = "Chiang Mai", .temp = 25.8 },
    WeatherStation{ .id = "Chicago", .temp = 9.8 },
    WeatherStation{ .id = "Chihuahua", .temp = 18.6 },
    WeatherStation{ .id = "Chișinău", .temp = 10.2 },
    WeatherStation{ .id = "Chittagong", .temp = 25.9 },
    WeatherStation{ .id = "Chongqing", .temp = 18.6 },
    WeatherStation{ .id = "Christchurch", .temp = 12.2 },
    WeatherStation{ .id = "City of San Marino", .temp = 11.8 },
    WeatherStation{ .id = "Colombo", .temp = 27.4 },
    WeatherStation{ .id = "Columbus", .temp = 11.7 },
    WeatherStation{ .id = "Conakry", .temp = 26.4 },
    WeatherStation{ .id = "Copenhagen", .temp = 9.1 },
    WeatherStation{ .id = "Cotonou", .temp = 27.2 },
    WeatherStation{ .id = "Cracow", .temp = 9.3 },
    WeatherStation{ .id = "Da Lat", .temp = 17.9 },
    WeatherStation{ .id = "Da Nang", .temp = 25.8 },
    WeatherStation{ .id = "Dakar", .temp = 24.0 },
    WeatherStation{ .id = "Dallas", .temp = 19.0 },
    WeatherStation{ .id = "Damascus", .temp = 17.0 },
    WeatherStation{ .id = "Dampier", .temp = 26.4 },
    WeatherStation{ .id = "Dar es Salaam", .temp = 25.8 },
    WeatherStation{ .id = "Darwin", .temp = 27.6 },
    WeatherStation{ .id = "Denpasar", .temp = 23.7 },
    WeatherStation{ .id = "Denver", .temp = 10.4 },
    WeatherStation{ .id = "Detroit", .temp = 10.0 },
    WeatherStation{ .id = "Dhaka", .temp = 25.9 },
    WeatherStation{ .id = "Dikson", .temp = -11.1 },
    WeatherStation{ .id = "Dili", .temp = 26.6 },
    WeatherStation{ .id = "Djibouti", .temp = 29.9 },
    WeatherStation{ .id = "Dodoma", .temp = 22.7 },
    WeatherStation{ .id = "Dolisie", .temp = 24.0 },
    WeatherStation{ .id = "Douala", .temp = 26.7 },
    WeatherStation{ .id = "Dubai", .temp = 26.9 },
    WeatherStation{ .id = "Dublin", .temp = 9.8 },
    WeatherStation{ .id = "Dunedin", .temp = 11.1 },
    WeatherStation{ .id = "Durban", .temp = 20.6 },
    WeatherStation{ .id = "Dushanbe", .temp = 14.7 },
    WeatherStation{ .id = "Edinburgh", .temp = 9.3 },
    WeatherStation{ .id = "Edmonton", .temp = 4.2 },
    WeatherStation{ .id = "El Paso", .temp = 18.1 },
    WeatherStation{ .id = "Entebbe", .temp = 21.0 },
    WeatherStation{ .id = "Erbil", .temp = 19.5 },
    WeatherStation{ .id = "Erzurum", .temp = 5.1 },
    WeatherStation{ .id = "Fairbanks", .temp = -2.3 },
    WeatherStation{ .id = "Fianarantsoa", .temp = 17.9 },
    WeatherStation{ .id = "Flores, Petén", .temp = 26.4 },
    WeatherStation{ .id = "Frankfurt", .temp = 10.6 },
    WeatherStation{ .id = "Fresno", .temp = 17.9 },
    WeatherStation{ .id = "Fukuoka", .temp = 17.0 },
    WeatherStation{ .id = "Gabès", .temp = 19.5 },
    WeatherStation{ .id = "Gaborone", .temp = 21.0 },
    WeatherStation{ .id = "Gagnoa", .temp = 26.0 },
    WeatherStation{ .id = "Gangtok", .temp = 15.2 },
    WeatherStation{ .id = "Garissa", .temp = 29.3 },
    WeatherStation{ .id = "Garoua", .temp = 28.3 },
    WeatherStation{ .id = "George Town", .temp = 27.9 },
    WeatherStation{ .id = "Ghanzi", .temp = 21.4 },
    WeatherStation{ .id = "Gjoa Haven", .temp = -14.4 },
    WeatherStation{ .id = "Guadalajara", .temp = 20.9 },
    WeatherStation{ .id = "Guangzhou", .temp = 22.4 },
    WeatherStation{ .id = "Guatemala City", .temp = 20.4 },
    WeatherStation{ .id = "Halifax", .temp = 7.5 },
    WeatherStation{ .id = "Hamburg", .temp = 9.7 },
    WeatherStation{ .id = "Hamilton", .temp = 13.8 },
    WeatherStation{ .id = "Hanga Roa", .temp = 20.5 },
    WeatherStation{ .id = "Hanoi", .temp = 23.6 },
    WeatherStation{ .id = "Harare", .temp = 18.4 },
    WeatherStation{ .id = "Harbin", .temp = 5.0 },
    WeatherStation{ .id = "Hargeisa", .temp = 21.7 },
    WeatherStation{ .id = "Hat Yai", .temp = 27.0 },
    WeatherStation{ .id = "Havana", .temp = 25.2 },
    WeatherStation{ .id = "Helsinki", .temp = 5.9 },
    WeatherStation{ .id = "Heraklion", .temp = 18.9 },
    WeatherStation{ .id = "Hiroshima", .temp = 16.3 },
    WeatherStation{ .id = "Ho Chi Minh City", .temp = 27.4 },
    WeatherStation{ .id = "Hobart", .temp = 12.7 },
    WeatherStation{ .id = "Hong Kong", .temp = 23.3 },
    WeatherStation{ .id = "Honiara", .temp = 26.5 },
    WeatherStation{ .id = "Honolulu", .temp = 25.4 },
    WeatherStation{ .id = "Houston", .temp = 20.8 },
    WeatherStation{ .id = "Ifrane", .temp = 11.4 },
    WeatherStation{ .id = "Indianapolis", .temp = 11.8 },
    WeatherStation{ .id = "Iqaluit", .temp = -9.3 },
    WeatherStation{ .id = "Irkutsk", .temp = 1.0 },
    WeatherStation{ .id = "Istanbul", .temp = 13.9 },
    WeatherStation{ .id = "İzmir", .temp = 17.9 },
    WeatherStation{ .id = "Jacksonville", .temp = 20.3 },
    WeatherStation{ .id = "Jakarta", .temp = 26.7 },
    WeatherStation{ .id = "Jayapura", .temp = 27.0 },
    WeatherStation{ .id = "Jerusalem", .temp = 18.3 },
    WeatherStation{ .id = "Johannesburg", .temp = 15.5 },
    WeatherStation{ .id = "Jos", .temp = 22.8 },
    WeatherStation{ .id = "Juba", .temp = 27.8 },
    WeatherStation{ .id = "Kabul", .temp = 12.1 },
    WeatherStation{ .id = "Kampala", .temp = 20.0 },
    WeatherStation{ .id = "Kandi", .temp = 27.7 },
    WeatherStation{ .id = "Kankan", .temp = 26.5 },
    WeatherStation{ .id = "Kano", .temp = 26.4 },
    WeatherStation{ .id = "Kansas City", .temp = 12.5 },
    WeatherStation{ .id = "Karachi", .temp = 26.0 },
    WeatherStation{ .id = "Karonga", .temp = 24.4 },
    WeatherStation{ .id = "Kathmandu", .temp = 18.3 },
    WeatherStation{ .id = "Khartoum", .temp = 29.9 },
    WeatherStation{ .id = "Kingston", .temp = 27.4 },
    WeatherStation{ .id = "Kinshasa", .temp = 25.3 },
    WeatherStation{ .id = "Kolkata", .temp = 26.7 },
    WeatherStation{ .id = "Kuala Lumpur", .temp = 27.3 },
    WeatherStation{ .id = "Kumasi", .temp = 26.0 },
    WeatherStation{ .id = "Kunming", .temp = 15.7 },
    WeatherStation{ .id = "Kuopio", .temp = 3.4 },
    WeatherStation{ .id = "Kuwait City", .temp = 25.7 },
    WeatherStation{ .id = "Kyiv", .temp = 8.4 },
    WeatherStation{ .id = "Kyoto", .temp = 15.8 },
    WeatherStation{ .id = "La Ceiba", .temp = 26.2 },
    WeatherStation{ .id = "La Paz", .temp = 23.7 },
    WeatherStation{ .id = "Lagos", .temp = 26.8 },
    WeatherStation{ .id = "Lahore", .temp = 24.3 },
    WeatherStation{ .id = "Lake Havasu City", .temp = 23.7 },
    WeatherStation{ .id = "Lake Tekapo", .temp = 8.7 },
    WeatherStation{ .id = "Las Palmas de Gran Canaria", .temp = 21.2 },
    WeatherStation{ .id = "Las Vegas", .temp = 20.3 },
    WeatherStation{ .id = "Launceston", .temp = 13.1 },
    WeatherStation{ .id = "Lhasa", .temp = 7.6 },
    WeatherStation{ .id = "Libreville", .temp = 25.9 },
    WeatherStation{ .id = "Lisbon", .temp = 17.5 },
    WeatherStation{ .id = "Livingstone", .temp = 21.8 },
    WeatherStation{ .id = "Ljubljana", .temp = 10.9 },
    WeatherStation{ .id = "Lodwar", .temp = 29.3 },
    WeatherStation{ .id = "Lomé", .temp = 26.9 },
    WeatherStation{ .id = "London", .temp = 11.3 },
    WeatherStation{ .id = "Los Angeles", .temp = 18.6 },
    WeatherStation{ .id = "Louisville", .temp = 13.9 },
    WeatherStation{ .id = "Luanda", .temp = 25.8 },
    WeatherStation{ .id = "Lubumbashi", .temp = 20.8 },
    WeatherStation{ .id = "Lusaka", .temp = 19.9 },
    WeatherStation{ .id = "Luxembourg City", .temp = 9.3 },
    WeatherStation{ .id = "Lviv", .temp = 7.8 },
    WeatherStation{ .id = "Lyon", .temp = 12.5 },
    WeatherStation{ .id = "Madrid", .temp = 15.0 },
    WeatherStation{ .id = "Mahajanga", .temp = 26.3 },
    WeatherStation{ .id = "Makassar", .temp = 26.7 },
    WeatherStation{ .id = "Makurdi", .temp = 26.0 },
    WeatherStation{ .id = "Malabo", .temp = 26.3 },
    WeatherStation{ .id = "Malé", .temp = 28.0 },
    WeatherStation{ .id = "Managua", .temp = 27.3 },
    WeatherStation{ .id = "Manama", .temp = 26.5 },
    WeatherStation{ .id = "Mandalay", .temp = 28.0 },
    WeatherStation{ .id = "Mango", .temp = 28.1 },
    WeatherStation{ .id = "Manila", .temp = 28.4 },
    WeatherStation{ .id = "Maputo", .temp = 22.8 },
    WeatherStation{ .id = "Marrakesh", .temp = 19.6 },
    WeatherStation{ .id = "Marseille", .temp = 15.8 },
    WeatherStation{ .id = "Maun", .temp = 22.4 },
    WeatherStation{ .id = "Medan", .temp = 26.5 },
    WeatherStation{ .id = "Mek'ele", .temp = 22.7 },
    WeatherStation{ .id = "Melbourne", .temp = 15.1 },
    WeatherStation{ .id = "Memphis", .temp = 17.2 },
    WeatherStation{ .id = "Mexicali", .temp = 23.1 },
    WeatherStation{ .id = "Mexico City", .temp = 17.5 },
    WeatherStation{ .id = "Miami", .temp = 24.9 },
    WeatherStation{ .id = "Milan", .temp = 13.0 },
    WeatherStation{ .id = "Milwaukee", .temp = 8.9 },
    WeatherStation{ .id = "Minneapolis", .temp = 7.8 },
    WeatherStation{ .id = "Minsk", .temp = 6.7 },
    WeatherStation{ .id = "Mogadishu", .temp = 27.1 },
    WeatherStation{ .id = "Mombasa", .temp = 26.3 },
    WeatherStation{ .id = "Monaco", .temp = 16.4 },
    WeatherStation{ .id = "Moncton", .temp = 6.1 },
    WeatherStation{ .id = "Monterrey", .temp = 22.3 },
    WeatherStation{ .id = "Montreal", .temp = 6.8 },
    WeatherStation{ .id = "Moscow", .temp = 5.8 },
    WeatherStation{ .id = "Mumbai", .temp = 27.1 },
    WeatherStation{ .id = "Murmansk", .temp = 0.6 },
    WeatherStation{ .id = "Muscat", .temp = 28.0 },
    WeatherStation{ .id = "Mzuzu", .temp = 17.7 },
    WeatherStation{ .id = "N'Djamena", .temp = 28.3 },
    WeatherStation{ .id = "Naha", .temp = 23.1 },
    WeatherStation{ .id = "Nairobi", .temp = 17.8 },
    WeatherStation{ .id = "Nakhon Ratchasima", .temp = 27.3 },
    WeatherStation{ .id = "Napier", .temp = 14.6 },
    WeatherStation{ .id = "Napoli", .temp = 15.9 },
    WeatherStation{ .id = "Nashville", .temp = 15.4 },
    WeatherStation{ .id = "Nassau", .temp = 24.6 },
    WeatherStation{ .id = "Ndola", .temp = 20.3 },
    WeatherStation{ .id = "New Delhi", .temp = 25.0 },
    WeatherStation{ .id = "New Orleans", .temp = 20.7 },
    WeatherStation{ .id = "New York City", .temp = 12.9 },
    WeatherStation{ .id = "Ngaoundéré", .temp = 22.0 },
    WeatherStation{ .id = "Niamey", .temp = 29.3 },
    WeatherStation{ .id = "Nicosia", .temp = 19.7 },
    WeatherStation{ .id = "Niigata", .temp = 13.9 },
    WeatherStation{ .id = "Nouadhibou", .temp = 21.3 },
    WeatherStation{ .id = "Nouakchott", .temp = 25.7 },
    WeatherStation{ .id = "Novosibirsk", .temp = 1.7 },
    WeatherStation{ .id = "Nuuk", .temp = -1.4 },
    WeatherStation{ .id = "Odesa", .temp = 10.7 },
    WeatherStation{ .id = "Odienné", .temp = 26.0 },
    WeatherStation{ .id = "Oklahoma City", .temp = 15.9 },
    WeatherStation{ .id = "Omaha", .temp = 10.6 },
    WeatherStation{ .id = "Oranjestad", .temp = 28.1 },
    WeatherStation{ .id = "Oslo", .temp = 5.7 },
    WeatherStation{ .id = "Ottawa", .temp = 6.6 },
    WeatherStation{ .id = "Ouagadougou", .temp = 28.3 },
    WeatherStation{ .id = "Ouahigouya", .temp = 28.6 },
    WeatherStation{ .id = "Ouarzazate", .temp = 18.9 },
    WeatherStation{ .id = "Oulu", .temp = 2.7 },
    WeatherStation{ .id = "Palembang", .temp = 27.3 },
    WeatherStation{ .id = "Palermo", .temp = 18.5 },
    WeatherStation{ .id = "Palm Springs", .temp = 24.5 },
    WeatherStation{ .id = "Palmerston North", .temp = 13.2 },
    WeatherStation{ .id = "Panama City", .temp = 28.0 },
    WeatherStation{ .id = "Parakou", .temp = 26.8 },
    WeatherStation{ .id = "Paris", .temp = 12.3 },
    WeatherStation{ .id = "Perth", .temp = 18.7 },
    WeatherStation{ .id = "Petropavlovsk-Kamchatsky", .temp = 1.9 },
    WeatherStation{ .id = "Philadelphia", .temp = 13.2 },
    WeatherStation{ .id = "Phnom Penh", .temp = 28.3 },
    WeatherStation{ .id = "Phoenix", .temp = 23.9 },
    WeatherStation{ .id = "Pittsburgh", .temp = 10.8 },
    WeatherStation{ .id = "Podgorica", .temp = 15.3 },
    WeatherStation{ .id = "Pointe-Noire", .temp = 26.1 },
    WeatherStation{ .id = "Pontianak", .temp = 27.7 },
    WeatherStation{ .id = "Port Moresby", .temp = 26.9 },
    WeatherStation{ .id = "Port Sudan", .temp = 28.4 },
    WeatherStation{ .id = "Port Vila", .temp = 24.3 },
    WeatherStation{ .id = "Port-Gentil", .temp = 26.0 },
    WeatherStation{ .id = "Portland (OR)", .temp = 12.4 },
    WeatherStation{ .id = "Porto", .temp = 15.7 },
    WeatherStation{ .id = "Prague", .temp = 8.4 },
    WeatherStation{ .id = "Praia", .temp = 24.4 },
    WeatherStation{ .id = "Pretoria", .temp = 18.2 },
    WeatherStation{ .id = "Pyongyang", .temp = 10.8 },
    WeatherStation{ .id = "Rabat", .temp = 17.2 },
    WeatherStation{ .id = "Rangpur", .temp = 24.4 },
    WeatherStation{ .id = "Reggane", .temp = 28.3 },
    WeatherStation{ .id = "Reykjavík", .temp = 4.3 },
    WeatherStation{ .id = "Riga", .temp = 6.2 },
    WeatherStation{ .id = "Riyadh", .temp = 26.0 },
    WeatherStation{ .id = "Rome", .temp = 15.2 },
    WeatherStation{ .id = "Roseau", .temp = 26.2 },
    WeatherStation{ .id = "Rostov-on-Don", .temp = 9.9 },
    WeatherStation{ .id = "Sacramento", .temp = 16.3 },
    WeatherStation{ .id = "Saint Petersburg", .temp = 5.8 },
    WeatherStation{ .id = "Saint-Pierre", .temp = 5.7 },
    WeatherStation{ .id = "Salt Lake City", .temp = 11.6 },
    WeatherStation{ .id = "San Antonio", .temp = 20.8 },
    WeatherStation{ .id = "San Diego", .temp = 17.8 },
    WeatherStation{ .id = "San Francisco", .temp = 14.6 },
    WeatherStation{ .id = "San Jose", .temp = 16.4 },
    WeatherStation{ .id = "San José", .temp = 22.6 },
    WeatherStation{ .id = "San Juan", .temp = 27.2 },
    WeatherStation{ .id = "San Salvador", .temp = 23.1 },
    WeatherStation{ .id = "Sana'a", .temp = 20.0 },
    WeatherStation{ .id = "Santo Domingo", .temp = 25.9 },
    WeatherStation{ .id = "Sapporo", .temp = 8.9 },
    WeatherStation{ .id = "Sarajevo", .temp = 10.1 },
    WeatherStation{ .id = "Saskatoon", .temp = 3.3 },
    WeatherStation{ .id = "Seattle", .temp = 11.3 },
    WeatherStation{ .id = "Ségou", .temp = 28.0 },
    WeatherStation{ .id = "Seoul", .temp = 12.5 },
    WeatherStation{ .id = "Seville", .temp = 19.2 },
    WeatherStation{ .id = "Shanghai", .temp = 16.7 },
    WeatherStation{ .id = "Singapore", .temp = 27.0 },
    WeatherStation{ .id = "Skopje", .temp = 12.4 },
    WeatherStation{ .id = "Sochi", .temp = 14.2 },
    WeatherStation{ .id = "Sofia", .temp = 10.6 },
    WeatherStation{ .id = "Sokoto", .temp = 28.0 },
    WeatherStation{ .id = "Split", .temp = 16.1 },
    WeatherStation{ .id = "St. John's", .temp = 5.0 },
    WeatherStation{ .id = "St. Louis", .temp = 13.9 },
    WeatherStation{ .id = "Stockholm", .temp = 6.6 },
    WeatherStation{ .id = "Surabaya", .temp = 27.1 },
    WeatherStation{ .id = "Suva", .temp = 25.6 },
    WeatherStation{ .id = "Suwałki", .temp = 7.2 },
    WeatherStation{ .id = "Sydney", .temp = 17.7 },
    WeatherStation{ .id = "Tabora", .temp = 23.0 },
    WeatherStation{ .id = "Tabriz", .temp = 12.6 },
    WeatherStation{ .id = "Taipei", .temp = 23.0 },
    WeatherStation{ .id = "Tallinn", .temp = 6.4 },
    WeatherStation{ .id = "Tamale", .temp = 27.9 },
    WeatherStation{ .id = "Tamanrasset", .temp = 21.7 },
    WeatherStation{ .id = "Tampa", .temp = 22.9 },
    WeatherStation{ .id = "Tashkent", .temp = 14.8 },
    WeatherStation{ .id = "Tauranga", .temp = 14.8 },
    WeatherStation{ .id = "Tbilisi", .temp = 12.9 },
    WeatherStation{ .id = "Tegucigalpa", .temp = 21.7 },
    WeatherStation{ .id = "Tehran", .temp = 17.0 },
    WeatherStation{ .id = "Tel Aviv", .temp = 20.0 },
    WeatherStation{ .id = "Thessaloniki", .temp = 16.0 },
    WeatherStation{ .id = "Thiès", .temp = 24.0 },
    WeatherStation{ .id = "Tijuana", .temp = 17.8 },
    WeatherStation{ .id = "Timbuktu", .temp = 28.0 },
    WeatherStation{ .id = "Tirana", .temp = 15.2 },
    WeatherStation{ .id = "Toamasina", .temp = 23.4 },
    WeatherStation{ .id = "Tokyo", .temp = 15.4 },
    WeatherStation{ .id = "Toliara", .temp = 24.1 },
    WeatherStation{ .id = "Toluca", .temp = 12.4 },
    WeatherStation{ .id = "Toronto", .temp = 9.4 },
    WeatherStation{ .id = "Tripoli", .temp = 20.0 },
    WeatherStation{ .id = "Tromsø", .temp = 2.9 },
    WeatherStation{ .id = "Tucson", .temp = 20.9 },
    WeatherStation{ .id = "Tunis", .temp = 18.4 },
    WeatherStation{ .id = "Ulaanbaatar", .temp = -0.4 },
    WeatherStation{ .id = "Upington", .temp = 20.4 },
    WeatherStation{ .id = "Ürümqi", .temp = 7.4 },
    WeatherStation{ .id = "Vaduz", .temp = 10.1 },
    WeatherStation{ .id = "Valencia", .temp = 18.3 },
    WeatherStation{ .id = "Valletta", .temp = 18.8 },
    WeatherStation{ .id = "Vancouver", .temp = 10.4 },
    WeatherStation{ .id = "Veracruz", .temp = 25.4 },
    WeatherStation{ .id = "Vienna", .temp = 10.4 },
    WeatherStation{ .id = "Vientiane", .temp = 25.9 },
    WeatherStation{ .id = "Villahermosa", .temp = 27.1 },
    WeatherStation{ .id = "Vilnius", .temp = 6.0 },
    WeatherStation{ .id = "Virginia Beach", .temp = 15.8 },
    WeatherStation{ .id = "Vladivostok", .temp = 4.9 },
    WeatherStation{ .id = "Warsaw", .temp = 8.5 },
    WeatherStation{ .id = "Washington, D.C.", .temp = 14.6 },
    WeatherStation{ .id = "Wau", .temp = 27.8 },
    WeatherStation{ .id = "Wellington", .temp = 12.9 },
    WeatherStation{ .id = "Whitehorse", .temp = -0.1 },
    WeatherStation{ .id = "Wichita", .temp = 13.9 },
    WeatherStation{ .id = "Willemstad", .temp = 28.0 },
    WeatherStation{ .id = "Winnipeg", .temp = 3.0 },
    WeatherStation{ .id = "Wrocław", .temp = 9.6 },
    WeatherStation{ .id = "Xi'an", .temp = 14.1 },
    WeatherStation{ .id = "Yakutsk", .temp = -8.8 },
    WeatherStation{ .id = "Yangon", .temp = 27.5 },
    WeatherStation{ .id = "Yaoundé", .temp = 23.8 },
    WeatherStation{ .id = "Yellowknife", .temp = -4.3 },
    WeatherStation{ .id = "Yerevan", .temp = 12.4 },
    WeatherStation{ .id = "Yinchuan", .temp = 9.0 },
    WeatherStation{ .id = "Zagreb", .temp = 10.7 },
    WeatherStation{ .id = "Zanzibar City", .temp = 26.0 },
    WeatherStation{ .id = "Zürich", .temp = 9.3 }
};

// Change this for a custom file size
const LINE_COUNT = 1_000_000_000;

pub fn main() !void {
    std.debug.print("Starting measurements generation\n", .{});

    var timer = try std.time.Timer.start();

    // page size is usually 4KB and for the optimal buffer size we need 64-128KB
    const buffer_size = std.heap.pageSize() << 4;

    var stdout_buffer: [buffer_size]u8 = undefined;

    const cwd = std.fs.cwd();

    var file = try cwd.createFile(file_path, .{ .truncate = true });
    defer file.close();

    var file_writer = file.writer(&stdout_buffer);
    var writer = &file_writer.interface;

    for (0..LINE_COUNT) |_| {
        const randint = std.crypto.random.int(u16);
        const idx = @mod(randint, stations.len);

        try writer.writeAll(stations[idx].id);
        try writer.writeByte(';');

        var tempF: f32 = stations[idx].measurement();

        if (tempF < 0) {
            try writer.writeByte('-');
            tempF = -tempF;
        }

        const base     : u8 = @as(u8, @intFromFloat(tempF));
        const exponent : u8 = @as(u8, @intCast(@as(u16, @intFromFloat(tempF * 10)) - @as(u16, base * 10)));
        const firstDig : u8 = @divFloor(base, 10);
        const secondDig: u8 = base - firstDig * 10;

        if (firstDig != 0) {
            try writer.writeByte('0' + firstDig);
        }

        try writer.writeByte('0' + secondDig);
        try writer.writeByte('.');
        try writer.writeByte('0' + exponent);
        try writer.writeByte('\n');
    }

    try writer.flush();

    const elapsed_ns = timer.read();
    const elapsed_ms = @as(f64, @floatFromInt(elapsed_ns)) / std.time.ns_per_ms;

    std.debug.print("Done in {d} milliseconds.", .{ elapsed_ms });
}
